### ISSUE TITLE
mobile.twitter.com can’t be flattr’d

### ISSUE THREAD

**Issue by da2x** [flattr/flattr-extension#44] opened 2018-05-29 13:19 UTC
**Environment**

* Flattr version: 0.6.0.9
* Browser name and version: Firefox 60
* OS name and version: macOS 10.13

**Steps to reproduce**

1. Open https://mobile.twitter.com/gamingonlinux/status/1001030089616904192
2. Click the Flattr button in the extension pop-out

**Observed behavior**

No flattrs.

**Expected behavior**

+1 flattr.

**Comment by ThomasGreiner** [comment] 2018-06-01 11:10
I can reproduce this issue. While on Chrome automatic flattring is disabled because mobile.twitter.com is not on our domains list - which should also be fixed - on Firefox it looks like it's enabled but no attention is being gathered which sounds similar to #21.

**Comment by ThomasGreiner** [comment] 2018-06-01 11:28
I was able to verify that this issue will be resolved with the fix we made for #21 which will be included in the next extension update.

**Closed by ThomasGreiner** 2018-06-01 11:28 UTC
Labels: bug
